# Generated by Django 3.1.4 on 2020-12-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20201214_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='beschreibung',
        ),
    ]
