# Generated by Django 3.1.4 on 2020-12-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_project_beschreibung'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='inhalt',
            field=models.CharField(default='Text', max_length=250),
        ),
    ]
